### ISSUE TITLE
Energy_tariff compilation error in ESPHome version 2025.12.3

### ISSUE THREAD

**Issue by ZampTM** [dentra/esphome-components#85]
In esphome version 2025.12.3 I can't compile the project with your external components due to the following error:

In file included from src/esphome/components/energy_tariffs/energy_tariff.h:10,
                 from src/esphome/components/energy_tariffs/energy_tariff.cpp:3:
src/esphome/components/api/custom_api_device.h: In instantiation of 'void esphome::api::CustomAPIDevice::register_service(void (T::*)(Ts ...), const string&, const std::array<std::__cxx11::basic_string<char>, sizeof... (Ts)>&) [with T = esphome::energy_tariffs::EnergyTariff; Ts = {float}; std::string = std::__cxx11::basic_string<char>]':
src/esphome/components/energy_tariffs/energy_tariff.cpp:33:92:   required from here
src/esphome/components/api/custom_api_device.h:73:19: error: static assertion failed: register_service() requires 'custom_services: true' in the 'api:' section of your YAML configuration
   73 |         sizeof(T) == 0,
      |         ~~~~~~~~~~^~~~
*** [.pioenvs/pzem_004t_12f/src/esphome/components/energy_tariffs/energy_tariff.cpp.o] Error 1
========================= [FAILED] Took 79.93 seconds =========================

**Comment by dentra** [comment]
thanks, fixed. now works with esphome 2026.3 and up
