### ISSUE TITLE
Could not compile the node with miot_mccgq02hl component, after update ESPHome to 2022.2.4 version

### ISSUE THREAD

**Issue by dbarlocker** [dentra/esphome-components#23]
Could not compile the node with miot_mccgq02hl component, after update ESPHome to 2022.2.4 version

[logs_living-room-node_upload.txt](https://github.com/dentra/esphome-components/files/8344478/logs_living-room-node_upload.txt)
INFO Reading configuration /config/esphome/living-room-node.yaml...
ERROR Unable to load component miot_mccgq02hl.binary_sensor:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/2f2a5be3/components/miot_mccgq02hl/binary_sensor.py", line 23, in <module>
    binary_sensor.binary_sensor_schema(MiotMCCGQ02HL, device_class=DEVICE_CLASS_OPENING)
AttributeError: module 'esphome.components.binary_sensor' has no attribute 'binary_sensor_schema'
Failed config

binary_sensor.miot_mccgq02hl: [source /config/esphome/living-room-node.yaml:44]
  
  Platform not found: 'binary_sensor.miot_mccgq02hl'.
  platform: miot_mccgq02hl
  mac_address: E4:AA:EC:35:0D:1A
  name: Front Door Sensor
  light: 
    name: Front Door Light Sensor
  alert: 
    name: Front Door Alert
  battery_level: 
    name: Front Door Battery Level
  battery_voltage: 
    name: Front Door Battery Voltage

**Comment by dentra** [comment]
You need to update ESPHome to 2022.3.0 and higher.

**Comment by dentra** [comment]
The problem is most likely solved. Issue will be closed soon.
