### ISSUE TITLE
Failed to compile on the lastest esphome version 2025.7.5 for the backup compoment

### ISSUE THREAD

**Issue by roumano** [dentra/esphome-components#77]
If i update esphome to the lastest version (2025.7.5), i can't compile anymore with your external_components due to this error : 
```
src/esphome/components/backup/backup.h:28:8: error: 'bool esphome::backup::Backup::canHandle(AsyncWebServerRequest*)' marked 'override', but does not override
```

i'm using it, only for the backup, with this configuration : 
```
external_components:
  - source: github://dentra/esphome-components
backup:
```

**Comment by dentra** [comment]
thanks. fix already in master branch

**Comment by X-Ryl669** [comment]
Hi, there's something wrong in the master branch currently. I still get: 
```
src/esphome/components/backup/backup.cpp: In member function 'virtual void esphome::backup::Backup::handleRequest(AsyncWebServerRequest*)':
src/esphome/components/backup/backup.cpp:49:118: warning: 'AsyncWebServerResponse* AsyncWebServerRequest::beginResponse_P(int, const arduino::String&, const uint8_t*, size_t, AwsTemplateProcessor)' is deprecated: Replaced by beginResponse(int code, const String& contentType, const uint8_t* content, size_t len, AwsTemplateProcessor callback = nullptr) [-Wdeprecated-declarations]
   49 |   auto *response = request->beginResponse_P(200, "plain/text;charset=UTF-8", ESPHOME_BACKUP_DATA, ESPHOME_BACKUP_SIZE);
      |                                                                                                                      ^
In file included from src/esphome/components/web_server_base/web_server_base.h:11,
                 from src/esphome/components/backup/backup.h:7,
                 from src/esphome/components/backup/backup.cpp:8:
.piolibdeps/ir-remote-chambre-nord/ESPAsyncWebServer/src/ESPAsyncWebServer.h:497:27: note: declared here
  497 |   AsyncWebServerResponse *beginResponse_P(int code, const String &contentType, const uint8_t *content, size_t len, AwsTemplateProcessor callback = nullptr) {
```

When compiling for a libretiny target (tuya's modules). I'm pretty sure the `#ifdef ESPIDF` part in the last commit code is too restrictive.
