### PR TITLE
Change to fix building error for backup component starting with ESPHome 2025.7.x

### LINKED ISSUE #77: Failed to compile on the lastest esphome version 2025.7.5 for the backup compoment
If i update esphome to the lastest version (2025.7.5), i can't compile anymore with your external_components due to this error : 
```
src/esphome/components/backup/backup.h:28:8: error: 'bool esphome::backup::Backup::canHandle(AsyncWebServerRequest*)' marked 'override', but does not override
```

i'm using it, only for the backup, with this configuration : 
```
external_components:
  - source: github://dentra/esphome-components
backup:
```

### PR DESCRIPTION
**Pull request by X-Ryl669**
Fixes #77 

Simple change in upstream class interface that needs to be propagated downstream.

### CODE REVIEW

**Comment by dentra** [comment]
thanks. added support the latest 2025.8 and also previous versions
