### ISSUE TITLE
Could not compiling the node with startup component, after update ESPHome to 2021.10.2 version

### ISSUE THREAD

**Issue by akalagov** [dentra/esphome-components#10]
```
|   |-- <ESP8266WiFi> 1.0
Compiling .pioenvs/entrance-air-curtain/src/esphome/components/startup/startup.cpp.o
Compiling .pioenvs/entrance-air-curtain/src/main.cpp.o
src/esphome/components/startup/startup.cpp: In constructor 'esphome::startup::StartupSensor::StartupSensor()':
src/esphome/components/startup/startup.cpp:11:48: error: 'millis' was not declared in this scope
 StartupSensor::StartupSensor() : start_(millis()){};
                                                ^
src/esphome/components/startup/startup.cpp: In member function 'virtual void esphome::startup::StartupSensor::loop()':
src/esphome/components/startup/startup.cpp:32:44: error: 'millis' was not declared in this scope
   this->startup_ = now.timestamp - (millis() - this->start_) / 1000;
                                            ^
*** [.pioenvs/entrance-air-curtain/src/esphome/components/startup/startup.cpp.o] Error 1
========================== [FAILED] Took 5.35 seconds ==========================
```
